.github/workflows/keewe_test.yaml
package.json

[Feature][개발환경설정] 빌드테스트 추가

---

App.tsx
components/BlackNextButton.tsx
components/SocialLoginButton.tsx
navigation/index.tsx
screens/SignUpScreen.tsx
types.tsx

- 로그인 스크린 구현
- SocialLoginButton 컴포넌트 제작.

[Feature][온보딩]로그인 화면 구현

---

App.tsx
components/BlackNextButton.tsx
components/EditScreenInfo.tsx
components/TextInputDetail.tsx
screens/NicknameCreationScreen.tsx
theme/light.ts
tsconfig.json
types.tsx

[Feature][개발환경설정] 테마 설정

---

package-lock.json
package.json
src/components/accordions/Accordion.tsx

[Feature] [챌린지] Accordion 컴포넌트 구현

---

src/components/stepper/Stepper.tsx

[Feature][챌린지] 스태퍼 구현

---

App.tsx
src/components/texts/TextInputDetail.tsx
src/screens/challenge/CategoryCreateScreen.tsx
src/screens/challenge/ChallengeGoalSettingScreen.tsx
src/screens/challenge/ChallengeGoalSettingSection.tsx
types.tsx

[Feature][챌린지] Goal Setting Screen 구현

---

App.tsx
src/components/header/HeaderRightButton.tsx
src/components/texts/TextInputDetail.tsx
src/navigation/index.tsx
src/screens/challenge/ChallengeGoalSettingScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx
types.tsx

* Subject creation screen created
* right Button, and conditional button edited

[Feature][챌린지] Subject creation screen 구현

---

src/screens/challenge/CategoryCreateScreen.tsx
src/screens/challenge/ChallengeInfoScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx

* TextInputDetail Props 수정사항 적용

[Refactor][챌린지] TextInputDetail Props 수정사항 적용

---

src/components/texts/TextInputDetail.tsx
src/screens/challenge/ChallengeInfoScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx

* TextInputDetail의 errorMessage와 button의 작동 오류 fix

[Fix][챌린지] TextInputDetail의 errorMessage와 button fix

---

App.tsx
src/components/accordions/Accordion.tsx
src/components/buttons/ConditionalButton.tsx
src/screens/challenge/CategorySelectScreen.tsx
src/screens/challenge/ChallengeCreationApprovedScreen.tsx
src/screens/challenge/ChallengeGoalSettingScreen.tsx
src/screens/challenge/ChallengeGoalSettingSection.tsx
src/screens/challenge/ChallengeInfoScreen.tsx

* 스텝3 Range bar 인터렉션 수정
* 헤더 타이틀 다 없애기 성공
* 주 맞춤 완료
* 버튼 flex 없앰으로써 행동양식 수정

[Refactor][챌린지] #7,8,9,10 

---

src/components/header/HeaderRightButton.tsx
src/components/texts/SmallTextInput.tsx
src/screens/challenge/CategoryCreateScreen.tsx

[Feature][챌린지] SmallTextInput.tsx 구현

---

src/components/texts/CountingTextArea.tsx
src/components/texts/TextInputDetail.tsx
src/screens/challenge/ChallengeInfoSection.tsx

* ChallengeInfoSection의 구성요소들의 디자인과 기능 개선

[Refactor][챌린지] #4,5,6

---

App.tsx
src/components/texts/CountingTextArea.tsx
src/components/texts/TextInputDetail.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx

* headerBar title now aligns to center, 
* textInputDetail fixed for android
* subjectCreation now applied interest
* etc

[Refactor][챌린지] 헤더바 타이틀, 텍스트인풋, 헤더텍스트 부제 수정

---

src/components/bars/NumberProgressBar.tsx

[Feature][챌린지] ProgressBar 구현

---

App.tsx
package-lock.json
package.json
src/theme/light.ts

[Feature][환경설정] 폰트 적용

---

src/screens/challenge/CategoryCreateScreen.tsx

[Fix][챌린지] tag_create input disable 규칙 오타 수정

---

src/components/buttons/ConditionalButton.tsx
src/components/stepper/Stepper.tsx
src/navigation/index.tsx
src/screens/onboarding/ServiceIntroOneScreen.tsx
src/screens/onboarding/ServiceIntroThreeScreen.tsx
src/screens/onboarding/ServiceIntroTwoScreen.tsx

* Service Intro Containing styles has chagned
* Stepper.tsx steppers now have key, due to warning logs

[Refactor][온보딩] ServiceIntro Style refactored

---

package-lock.json
package.json
src/components/bars/SnackBar.tsx

[Feature][글쓰기] SnackBar Component 구현

---

App.tsx
src/components/header/HeaderBackButton.tsx
src/components/header/HeaderRightButton.tsx
src/screens/onboarding/InterestChooseScreen.tsx

* backgroundColor, slide animation, add margin to header button components

[Refactor][글쓰기] stack 전환에 따른 요소 수정

---

src/components/texts/StyledText.tsx

* fontFamily: pretendard Text styles should now use FontText component from StyledText

[Feature][개발환경설정] FontText component created

---

App.tsx
package-lock.json
package.json
src/components/cards/LinkCardForUpload.tsx
src/components/texts/BlandTextInput.tsx
src/components/texts/StyledText.tsx
src/navigation/index.tsx
src/screens/Main/BookMarkScreen.tsx
src/screens/Main/ChallengesScreen.tsx
src/screens/Main/Home.tsx
src/screens/Main/MainScreen.tsx
src/screens/Main/MyPageScreen.tsx
src/screens/Main/Tabs.tsx
src/screens/upload/EditButton.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/UploadScreen.tsx
src/types/upload.d.ts
src/utils/api/UploadAPIs.ts
types.tsx

* BottomTabNavigator 도입
* 글쓰기 리팩토링, 완료아님

[Feature][개발환경설정] BottomTabNavigator 도입

---

src/components/Folder/Folder.tsx
src/components/bars/SnackBar.tsx
src/components/cards/LinkCardForUpload.tsx
src/components/texts/StaticSizeScrollTextArea.tsx
src/components/texts/StyledText.tsx
src/screens/upload/EditButton.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/UploadScreen.tsx
src/types/upload.d.ts
src/utils/helper/fetchAPI/isValidLink.ts

* Snackbar has been added
* folder scrollview has been added to bottomsheetmodal

[Refactor][글쓰기] Snackbar and folder scrollview applied

---

App.tsx
src/components/profile/ProfileAvatar.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/screens/detailedPost/ShareScreen.tsx
src/utils/api/InsightAPI.ts

[Feat][상세게시글] ShareScreen profile added

---

src/components/bars/DividerBar.tsx
src/components/buttons/BottomFixButton.tsx
src/components/checkbox/CircularCheckbox.tsx
src/screens/Feed/FeedScreen.tsx
src/screens/Feed/TodayBubble.tsx
src/screens/Feed/UserSpecificChallengeSection.tsx
src/types/Feed/UserSpecificChallenge.d.ts
src/utils/api/UserSpecificChallenge.ts
src/utils/helper/UserSpecificChallengeDateFormatter/challengeTextFormatter.ts
src/utils/helper/UserSpecificChallengeDateFormatter/formatter.ts
src/utils/string/userSpecificDataDateInterval.ts

[Feat][Feed challenge] 홈화면 유저 챌린지 상세 정보 

---

src/components/buttons/tag.tsx
src/components/texts/CountingTextArea.tsx
src/components/texts/HeaderText.tsx
src/components/texts/TextInputDetail.tsx
src/screens/challenge/CategorySelectScreen.tsx
src/screens/challenge/ChallengeCategorySelectSection.tsx
src/screens/challenge/ChallengeGoalSettingBar.tsx
src/screens/challenge/ChallengeGoalSettingScreen.tsx
src/screens/challenge/ChallengeGoalSettingSection.tsx
src/screens/challenge/ChallengeInfoScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx

[챌린지][Refactor] QA 챌린지 생성 파트 90%완료

---

package-lock.json
package.json
src/components/Folder/Folder.tsx
src/components/header/HeaderRightButton.tsx
src/components/lotties/MainLottie.tsx
src/components/texts/TextInputDetail.tsx
src/screens/Feed/FeedScreen.tsx
src/screens/onboarding/ServiceIntroOneScreen.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/UploadScreen.tsx
src/utils/api/FeedAPI.ts
src/utils/helper/fetchAPI/isValidLink.ts

* 디자인 큐앤에이 처리
* 피드 스크롤뷰에서 위로 스와이프 시에 새로고침 됨.

[Refactor][Design QnA] 디자인 큐앤에이 수정 및 화면 리로드 

---

src/screens/detailedPost/DetailedPostScreen.tsx

##Refactor
- comment more button 수정

comment more button 수정

---

src/components/comments/CommentInput.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx

- 프로필 수정 기능 구현답글 더보기 개수 수정, Keyboard AvoidingView 수정

[Refactor][comment] 코멘트 개선사항 적용

---

src/components/profile/MypageProfile.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfileEditScreen.tsx
src/screens/Main/mypage/ProfileList.tsx
src/types/mypage.d.ts
src/utils/api/mypageAPI.ts

- 프로필 사진이 없을 시 현재 사진 삭제 버튼 비활성화
- 마이페이지 프로필 조회 get api

[Feature][마이페이지] 마이페이지 프로필 조회 API 연결

---

src/screens/detailedPost/ShareScreen.tsx

[Fix] [리팩토링] 쉐어링 개선

---

src/screens/Main/mypage/FolderOption.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/types/mypage.d.ts
src/utils/api/mypageAPI.ts

[Feature][마이페이지] 최근 획득 타이틀 3개 조회 API GET

---

src/components/emoticons/ReactIconButton.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/ShareScreen.tsx
src/screens/upload/UploadScreen.tsx
src/types/insight.d.ts
src/utils/api/InsightAPI.ts
src/utils/hooks/useGetUserId.ts

[Fix][버그] 각종 버그 수정

---

src/components/challenge/FeedScreenChallenge.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Feed/FeedList.tsx
src/screens/Main/mypage/FolderOption.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/NicknameEditingScreen.tsx
src/screens/Main/mypage/ProfileImage.tsx
src/screens/Main/mypage/ProfileScreen.tsx

- 완성도 다듬기
- 본인 프로필 클릭 시 마이페이지로 이동
- 아래로 당겼을 때 새로고침 동작
- 팔로우 api 연결

[Feature][마이페이지] 기능 추가

---

src/components/challenge/FeedScreenChallenge.tsx
src/components/comments/Comment.tsx
src/components/comments/CommentInput.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/types/insight/comments.d.ts

[Feat][Comment] 코멘트 리뉴얼

---

App.tsx
src/components/challenge/FeedScreenChallenge.tsx
src/components/comments/BSMyComment.tsx
src/components/comments/BSOthersComment.tsx
src/components/comments/Comment.tsx
src/components/comments/CommentVerticalDots.tsx
src/components/profile/MypageProfile.tsx
src/navigation/tabs/FollowTopTabs.tsx
src/screens/Feed/UserSpecificChallengeSection.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/screens/follow/FollowListSection.tsx
src/utils/api/UserSpecificChallenge.ts
types.tsx

* following numbers, item name, threedots, profile func, etc.

[Feat][JH-0212] following numbers, item name, threedots, profile func, etc.

---

package-lock.json
package.json
src/components/title/MypageTitle.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Main/mypage/InterestEditingScreen.tsx
src/screens/Main/mypage/IntroductionEditingScreen.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/NicknameEditingScreen.tsx
src/screens/Main/mypage/ProfileEditScreen.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/title/TitleScreen.tsx

- 남의 프로필 챌린지 버튼 뜨도록
- 북마크 스낵바 위치 교정
- 타이틀 목록에 이미지 추가
- 프로필 변경 api 적용

[Fix][마이페이지] 사소한 버그와 프로필 수정 기능

---

src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfileEditScreen.tsx

- 마이페이지의 프로필 query invalidation을 통해 즉각 반영 되도록 수정

[Fix][마이페이지] 프로필 수정 관련 이슈

---

App.tsx
src/components/comments/Comment.tsx
src/components/comments/CommentInput.tsx
src/constants/title/titleData.ts
src/screens/Feed/FeedList.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/ShareScreen.tsx

- 피드 오류 수정
- 상세 게시글 및 댓글 오류 수정
- 타이틀 스크린 오류 수정

[Fix] [피드스크린] 피드 로딩 오류 수정

---

src/screens/upload/UploadBottomContainer.tsx
src/screens/upload/UploadScreen.tsx
src/types/challenge.d.ts
src/utils/api/BaseHttpClient.ts
src/utils/api/FeedAPI.ts

[Feature] [공유] 공유하기 스크린 수정, 토큰 만료 로직 수정

---

App.tsx
src/screens/error/ErrorScreen.tsx
src/utils/api/BaseHttpClient.ts
types.tsx

[Feat][에러] 에러 스크린 구현

---

App.tsx
src/screens/Main/ChallengesScreen.tsx
src/screens/error/ErrorScreen.tsx
src/utils/api/BaseHttpClient.ts
types.tsx

[Fix][에러] 오류 수정

---

src/screens/Main/BookMarkScreen.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/utils/api/FeedAPI.ts
src/utils/hooks/feedInifiniteScroll/useInfiniteFeed.ts

- 북마크한 인사이트 조회 api 변동 사항 반영(cursor)

[Refactor][북마크] query cursor 변경

---

src/utils/api/FeedAPI.ts
src/utils/hooks/feedInifiniteScroll/useInfiniteFeed.ts

- useInfiniteFeed 의 수정으로 발생한 마이페이지 피드 무한 루프 에러 교정

[Fix][마이페이지] fixed feed infinite scroll

---

src/components/bottomsheet/SheetMyPostOptions.tsx
src/components/buttons/MultipleTapButton.tsx
src/components/comments/SheetOthersComment.tsx
src/components/texts/StaticSizeScrollTextArea.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Feed/FeedVerticalDots.tsx
src/screens/Main/Tabs.tsx
src/screens/settings/SettingsScreen.tsx
src/screens/upload/UploadScreen.tsx
src/types/upload.d.ts
src/utils/api/FeedAPI.ts
src/utils/api/UploadAPIs.ts
types.tsx

* insight edit (patch) is now added through edit using bottom sheet (three vertical dots) 
* root page has been removed 
* Tapping on version tab in SettingsScreen 5times within 2seconds navigates to Root Page

[Feat][Upload] Upload Patch feature added. 

---

src/screens/Main/challenge/InviteOptions.tsx

[Feature][챌린지] Challenge Invitation Share

---

src/navigation/index.tsx
src/screens/challenge/ChallengeJoinApprovedScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/screens/login/LoginScreen.tsx
src/screens/onboarding/NicknameCreationScreen.tsx
src/screens/statistics/FollowCountCard.tsx
src/screens/statistics/StatisticsLinkInfo.tsx
src/screens/statistics/StatisticsReactionCountInfo.tsx
src/screens/statistics/StatisticsReactionInfo.tsx
src/screens/statistics/StatisticsScreen.tsx
src/types/insight.d.ts
src/utils/api/InsightAPI.ts

[Feature][통계] 방문수 api 연결

---

src/screens/upload/UploadScreen.tsx

[Fix][인사이트 작성] 글쓰기 옵셔널 체이닝 수정

---

src/screens/Main/challenge/ChallengeReaction.tsx
src/screens/Main/challenge/constant.ts
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/statistics/StatisticsScreen.tsx
src/types/mypage.d.ts
src/types/statistics.d.ts
src/utils/api/FollowAPI.ts
src/utils/api/mypageAPI.ts

[Fix][QA] 버그픽스

---

src/screens/onboarding/InsightSampleScreen.tsx
src/utils/api/BaseHttpClient.ts
src/utils/api/ChallengeAPI.ts
src/utils/api/DetailedPostAPI.ts
src/utils/api/FeedAPI.ts
src/utils/api/FeedBookMark.ts
src/utils/api/FollowAPI.ts
src/utils/api/InsightAPI.ts
src/utils/api/OnboardAPI.ts
src/utils/api/StatisticsAPI.ts
src/utils/api/TitleAPI.ts
src/utils/api/UploadAPIs.ts
src/utils/api/UserSpecificChallenge.ts
src/utils/api/mypageAPI.ts

[Fix][QA] 토큰 만료상태 해결

---

src/screens/Main/ChallengesScreen.tsx

[Feature][ChallengeScreen] 챌린지 홈 헤더 타이틀 추가

---

src/components/texts/CountingTextArea.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/challenge/ChallengeInfoScreen.tsx
src/screens/login/LoginScreen.tsx
src/screens/onboarding/SignUpScreen.tsx
src/screens/settings/SettingsScreen.tsx
src/screens/settings/folderSettings/FolderEditScreen.tsx
src/utils/api/BaseHttpClient.ts
src/utils/api/ChallengeAPI.ts
src/utils/api/LoginAPI.ts
src/utils/api/mypageAPI.ts
src/utils/hooks/asyncStorage/Logout.ts

- 해결한 것
- 챌린지 생성 시, 챌린지 소개 글에 자음 1자만 나옴
- 폴더 편집 - 처리되지 않은 예외가 발생했어요. 
- 추가로 로그아웃 구현 중, 이슈 발생하여 승훈님에게 전달 위해 pr 생성

[Fix][QA] 로그아웃 시 재로그인 불가

---

src/screens/Main/ChallengesScreen.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/utils/api/mypageAPI.ts

[FIX][QA] mypage focus시 query 리셋

---

src/screens/Main/ChallengesScreen.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfileEditScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx
src/screens/detailedPost/ShareScreen.tsx
src/screens/login/LoginScreen.tsx
src/screens/settings/SettingsScreen.tsx
src/screens/upload/UploadScreen.tsx
src/utils/api/BaseHttpClient.ts
src/utils/api/FeedAPI.ts
src/utils/api/FeedBookMark.ts
src/utils/api/UserSpecificChallenge.ts
src/utils/api/followList/followList.ts
src/utils/api/followList/followersFollowings.ts
src/utils/api/mypageAPI.ts
src/utils/hooks/feedInifiniteScroll/useInfiniteFeed.ts

[Fix][QA] 로그아웃 탈퇴 시 앱 리로드 기능 추가

---

src/screens/Main/mypage/ProfileScreen.tsx
src/screens/challenge/ChallengeInfoScreen.tsx
src/types/mypage.d.ts
src/utils/api/FeedAPI.ts

- 남의 프로필의 챌린지 버튼을 누를 시, 
1. 기본적으로는 챌린지 참여 화면으로 이동
2. 해당 챌린지가 사용자 본인이 참여하고 있는 챌린지와 동일할 시, 곧바로 챌린지 상세화면으로 이동

[Feature][프로필] Challenge Button 활성화

---

src/screens/Main/challenge/ChallengeDetailScreen.tsx
src/screens/Main/mypage/MyPageScreen.tsx

[Fix][QA] 데이터 없을 시 데이터 처리

---

src/screens/Main/BookMarkScreen.tsx
src/screens/settings/SettingsScreen.tsx
src/types/Feed/Feedinsights.d.ts
src/utils/api/FeedAPI.ts

[Fix][로그아웃] Logout testing

---

app.json
src/screens/Feed/FeedScreen.tsx
src/screens/Feed/UserSpecificChallengeSection.tsx
src/screens/settings/SettingsScreen.tsx
src/utils/helper/logoutAndWithdraw/removeStackAndNavigate.ts

* 로그아웃 및 탈퇴를 했을때, 스택초기화 및 회원가입 페이지로 이동하게끔 되게함. 
* LoginScreen으로 가면 안되는거 이제 앎. 수정함
* resetAndReload 라는 헬퍼함수를 만들어서 이용 용이하게끔 만듦.

[Feat][Reset And Reload] 로그아웃 및 탈퇴시에 스택 초기화 및 네비게이션

---

src/utils/api/FeedAPI.ts

- Bookmark Get API 첫 cursor date 한국 시간으로 변경

[Fix][북마크] Bookmark한 인사이트 호출 API 첫 cursor date 한국 시간으로 변경

---

app.json
package-lock.json
package.json
src/screens/Main/challenge/ChallengeInvite.tsx
src/screens/Main/challenge/FollowersAndFollowings.tsx
src/utils/api/followList/followersFollowings.ts

- 초대 유저 검색 기능 구현
- lodash 사용
- eas 관련 문제 발생으로 app.json에 해당 코드 지워 놓음

[Feature][챌린지] 초대 유저 검색(Debounce)

---

src/screens/follow/FollowListSection.tsx
src/screens/settings/BlockListSection.tsx

[Fix][FollowList] 팔로우 버튼의 유저 id 가 로그인 유저id 와 일치할때 버튼이 뜨지 않도록 함

---

src/components/texts/BlandTextInput.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/settings/folderSettings/FolderEditScreen.tsx

[QA][설정] 폴더 편집 키보드 높이조절

---

app.json
src/components/profile/ChallengeUserProfile.tsx
src/screens/Main/challenge/ChallengeDetailScreen.tsx
src/types/challenge.d.ts

[QA][첼린지 상세]프로필 이동기능 추가

---

app.json
src/components/bottomsheet/SheetMyPostOptions.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Feed/FeedList.tsx
src/screens/Feed/FeedVerticalDots.tsx

[Fix][QA] 인사이트 삭제 API 연결

---

src/components/texts/CountingTextArea.tsx
src/screens/upload/LinkSheetContent.tsx

* CountingTextArea를 un controlled input component으로 변경을 함. 
* Multiline true를 디폴트로, multiline을 바꿀수 있게 함. 
#169

[Fix][UploadScreen] URL 인풋창에서 한글등을 입력하면 예상치못한 버그들이 발생이됨

---

src/components/cards/LinkCard.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Feed/FeedTextContent.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/screens/upload/UploadScreen.tsx
src/utils/api/notification/notification.ts

[QA][글쓰기] 인사이트 내부 디자인 수정 및 업로드 로직 수정

---

src/screens/Feed/FeedScreen.tsx
src/screens/Main/BookMarkScreen.tsx
src/screens/Main/ChallengesScreen.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/notification/NotificationScreen.tsx

- 모든 탭 리프레시 기능 추가
- 알람 갱신은 탭 진입 및 이동 시 + 리프레시 시

[QA][Tab] 모든 탭 리프레시 기능 추가

---

App.tsx
src/components/bottomsheet/SheetMyPostOptions.tsx
src/screens/upload/UploadScreen.tsx

- 글 삭제시 뒤로가기, queryclient provider문제 해결

[QA][Feed] 삭제 시 동작 오류 해결

---

App.tsx
src/components/comments/Comment.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/follow/FollowListSection.tsx
src/screens/settings/BlockListSection.tsx
types.tsx

[QA][마이프로필] 마이프로필 페이지 생성

---

App.tsx
src/components/bottomsheet/SheetPostOptions.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/ShareScreen.tsx
src/screens/settings/BlockListSection.tsx
src/screens/settings/BlockedScreen.tsx

[QA][디자인] 디자인 수정

---

src/screens/challenge/CategoryCreateScreen.tsx
src/screens/detailedPost/ShareScreen.tsx
src/screens/settings/BlockListSection.tsx
src/screens/settings/BlockedScreen.tsx
src/utils/api/DetailedPostAPI.ts

[QA][관심사 설정] 카테고리 직접추가 수정

---

src/components/bottomsheet/SheetPostOptions.tsx
src/components/comments/SheetOthersComment.tsx

* FeedItem bottom sheet report fixed
* comment Item bottom sheet report fixed

[Fix][BottomSheet QA] bottomsheet qa 에 대한 처리

---

src/components/comments/Comment.tsx

[QA][댓글] 삭제된 댓글 수정

---

src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx
src/screens/detailedPost/ShareScreen.tsx

* detailedPost Head text의 1/4번째 타이틀 쪽을 고침
* SharedScreen에 넘어가는 1/4번째 데이터 잘 넘어가게끔 함

[Insight][DetailedPost] 챌린지 기록에 대한 데이터 처리

---

src/components/profile/MypageProfile.tsx
src/screens/Feed/FeedList.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfilePageFolderSection.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/upload/UploadScreen.tsx

[QA] 노션 QA 할당된거, 다 쳐냄

---

src/components/comments/CommentInput.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/UploadBottomContainer.tsx
src/screens/upload/UploadScreen.tsx
src/types/insight.d.ts

[Fix][Upload] 업로드 api 연결

---

src/screens/settings/SettingsScreen.tsx

[Fix][LogOut] 애플 로그아웃 처리 추가

---

src/screens/Main/Tabs.tsx

[Fix][메인] 메인 팅김 버그 수정

---

app.json
src/components/comments/CommentInput.tsx
src/screens/detailedPost/CommentsScreen.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx

[Fix][댓글] 댓글 입력창 로직 변경

---

app.json
src/screens/Main/challenge/ChallengeDetailScreen.tsx

[Fix][친구수 수정] 친구수 수정

---

src/screens/challenge/ChallengeJoinScreen.tsx
src/screens/challenge/ChallengeSubjectCreationScreen.tsx

[Fix][챌린지] invalidate query 로직 추가

---

src/components/profile/MypageProfile.tsx
src/components/profile/ProfileAvatar.tsx
src/navigation/tabs/FollowTopTabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/Main/mypage/ProfileScreen.tsx
src/screens/follow/FollowListSection.tsx

프로필
- headerTitle 제거
- 프로필 이동 시 스택에 쌓이도록 수정
팔로잉 목록 페이지
- 디폴트 이미지 스타일 변경
- 팔로우 페이지 헤더 닉네임으로 수정

[Fix][Follow, Profile] 프로필 / 팔로우 목록 페이지 QA

---

src/components/texts/CountingTextArea.tsx
src/components/texts/StaticSizeScrollTextArea.tsx
src/screens/upload/LinkSheetContent.tsx
src/screens/upload/UploadScreen.tsx

[Fix][Upload] 업로드 에러 우회

---

src/screens/Main/challenge/ChallengeDetailScreen.tsx
src/screens/Main/challenge/ChallengeInvite.tsx
src/screens/Main/challenge/FollowersAndFollowings.tsx
src/types/challenge.d.ts
src/utils/api/ChallengeAPI.ts

[Feature][챌린지] 챌린지 초대 기능 추가

---

src/screens/settings/SettingsScreen.tsx

[Fix][설정] 로그아웃, 탈퇴 시 버그 수정

---

package-lock.json
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/detailedPost/DetailedPostSection.tsx

* 상세게시글 내에 가장 윗단의 [챌린지 명 ]      [챌린지 진행상황] 을 묶어버리는 pressable을 넣게함

[Fix][상세게시글] 챌린지 이름을 눌러도 챌린지상세로 이동하게끔 함

---

App.tsx
app.json
src/screens/link/LinkScreen.tsx
types.tsx

[Feat][링크] 딥링크 테스트페이지 추가

---

src/components/comments/Comment.tsx
src/components/profile/MiniProfile.tsx
src/screens/detailedPost/CommentsScreen.tsx

약간의 CSS 수정, 
댓글 작성하면 전체댓글이 하이라이트 되는 현상 수정.

[Fix][댓글] 작성한 댓글 하이라이트 버그 수정

---

App.tsx
app.json
src/navigation/index.tsx
src/utils/hooks/asyncStorage/Login.ts

[Feat][알람] expo token 로직 추가

---

App.tsx
app.json

[Feat][알람] 알람 테스트 추가

---

App.tsx
app.json
src/navigation/index.tsx

[Fix][에러] 에러 수정

---

App.tsx
app.json
src/navigation/index.tsx
src/screens/login/LoginScreen.tsx

[Refactor][알림] 푸쉬토큰 저장 로직 변경

---

App.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/link/LinkScreen.tsx

[Feat][앱링크] 앱링크 라우팅 적용

---

App.tsx
app.json

[Feat][앱링크] 링크 configure 위치 변경

---

App.tsx
app.json
src/screens/link/LinkScreen.tsx

[Fix][앱링크] 버그 수정

---

app.json
src/screens/link/LinkScreen.tsx

[Fix][앱 링크] 에러 수정

---

src/screens/link/LinkScreen.tsx

[Fix] 앱링크 이동로직 변경

---

app.json
src/screens/challenge/ChallengeGoalSettingSection.tsx
src/screens/link/LinkScreen.tsx

[Fix][앱링크] 링크 이동로직 변경

---

app.json
src/screens/Main/Tabs.tsx

[Fix][QA] navigate error 수정

---

app.json
src/screens/Main/Tabs.tsx

[Fix][QA] 네이게이션 에러 수정

---

app.json
src/screens/Main/Tabs.tsx

[Feat][탭] 파라미터 리셋기능 추가

---

App.tsx
src/navigation/index.tsx
src/screens/Main/Tabs.tsx
src/screens/Main/mypage/MyPageScreen.tsx

[Fix][QA] 네비게이션 에러 수정

---

App.tsx
app.json

[Feat][앱 링크] 앱 스킴방식 추가

---

App.tsx
app.json
package-lock.json
package.json
src/components/bars/Toasts.tsx
src/components/texts/StaticSizeScrollTextArea.tsx
src/screens/Feed/FeedItem.tsx
src/screens/Feed/FeedScreen.tsx
src/screens/Feed/FeedTextContent.tsx
src/screens/Main/challenge/ChallengeEditScreen.tsx
src/screens/challenge/ChallengeGoalSettingSection.tsx
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/upload/UploadScreen.tsx
src/utils/helper/strings/isTextNotOnlySpace.ts

* 업로드를 할때, 공백만 존재하면 업로드를 안되게끔 함
* 디테일 포스트는, 처음 진입시에 인사이트 내용을 전달받음. 네트워크 리스폰스를 기다리지 않음.

[Feat] insight non whitespace

---

assets/svgs/rightXml.ts
src/components/challenge/ChallengeParticipationView.tsx
src/components/challenge/ThisWeekRecord.tsx
src/components/checkbox/CircularCheckbox.tsx
src/components/profile/ChallengeProfileCurrent.tsx
src/screens/Feed/FeedScreen.tsx
src/screens/Feed/UserSpecificChallengeSection.tsx
src/screens/Main/ChallengesScreen.tsx
src/theme/light.ts

- 피그마의 '230807 홈-챌린지홈-챌린지상세에 걸친 챌린지현황 UI 업데이트' 중
- 홈
- 챌린지 홈

[Feature][홈, 챌린지홈] 230807 홈-챌린지홈-챌린지상세에 걸친 챌린지현황 UI 업데이트1

---

src/components/challenge/ChallengeEndDate.tsx
src/components/challenge/ChallengeParticipationView.tsx
src/components/challenge/ChallengeStatusCalendar.tsx
src/components/challenge/ThisWeekRecord.tsx
src/components/header/ChallengeTitle.tsx
src/screens/Feed/UserSpecificChallengeSection.tsx
src/screens/Main/ChallengesScreen.tsx
src/screens/Main/challenge/ChallengeDetailScreen.tsx
src/screens/Main/challenge/ChallengeStatusSection.tsx
src/types/Feed/UserSpecificChallenge.d.ts
src/utils/api/UserSpecificChallenge.ts

- 챌린지 참여 시 에러 fix
- 참여중인 챌린지 상세 이동시 에러 fix
- 챌린지 진행 상황 달력 구현

[Feature][챌린지] 챌린지 상세 진행 상황 달력 구현

---

src/components/emoticons/ReactIconButton.tsx

- React native flying objects 적용

[Refactor][리액션] react-native-flying-objects 적용

---

package-lock.json
package.json
src/components/emoticons/ReactIconButton.tsx

[Refactor][패키지] flying object 버전 업

---

package-lock.json
package.json
src/components/emoticons/ReactIconButton.tsx

[Refactor] react-native-flying-objects 버전 업

---

package-lock.json
package.json
src/screens/detailedPost/DetailedPostScreen.tsx
src/screens/notification/NotificationScreen.tsx
src/utils/api/notification/notification.ts

[Feat][Notification] 알림 모두읽기 기능 추가

---

src/screens/settings/SettingsScreen.tsx
src/types/login.d.ts
src/utils/api/LoginAPI.ts

[Feat][Profile] 연결된 계정 UI 추가

---

package-lock.json
package.json
src/screens/Main/Tabs.tsx

[Fix] 앱링크 오류 수정

---

src/components/bars/Toasts.tsx
src/components/cards/LinkCard.tsx
src/components/profile/Profile.tsx

- 인사이트 상세 타이틀 작성 시간 텍스트 opacity 수정
- 링크 컴포넌트 보더 삭제
- 토스트 backdrop-filter 효과 적용

[Refactor][QA] 인사이트 상세, 토스트 UI 디자인 수정

---

app.json
src/components/texts/HeaderText.tsx
src/screens/Main/challenge/ChallengeParticipationScreen.tsx

[FIX][QA] 앱 아이디 수정, 헤더 텍스트 수정

---

src/screens/settings/SettingsScreen.tsx
src/screens/title/TitleScreen.tsx
src/screens/title/TitleSticker.tsx
src/utils/string/timeInterval.ts

- Insight Date 수정
- Title Screen 접근 시 유저별 로직 추가

[FIX][QA] insight Date 수정 및 타인의 title screen접근시 로직 추가

---

src/components/challenge/ChallengeStatusCalendar.tsx
src/components/texts/HeaderText.tsx
src/screens/Main/ChallengesScreen.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/challenge/CategoryCreateScreen.tsx
src/screens/onboarding/ServiceIntroScreen.tsx
src/utils/api/followList/followersFollowings.ts

- 챌린지 생성 후 확인 버튼을 누르면 발생하던 에러 제거
- 온보딩에서의 글씨 짤림 현상 제거
- 카테고리 직접 추가 screen에 마진 추가

[Fix] 챌린지 생성 후 에러 & 온보딩 짤림현상 제거

---

src/screens/detailedPost/CommentList.tsx
src/screens/detailedPost/ReplyList.tsx

refactor: 더보기 로직 변경

---

App.tsx
src/components/bars/Toasts.tsx
src/components/cards/LinkCard.tsx
src/screens/Feed/FeedLinkCard.tsx
src/screens/Feed/FeedTextContent.tsx

* 링크카드 롱프래스
* 피드 아이템의 더보기 앞의 ... 지움

[Feature][LinkCard] 링크카드를 1초간 롱프래스 시에, 링크가 복사가 됨 

---

src/components/bottomsheet/SheetPostOptions.tsx
src/components/comments/CommentVerticalDots.tsx
src/components/comments/SheetOthersComment.tsx
src/screens/Feed/FeedVerticalDots.tsx
src/screens/Main/mypage/MyPageScreen.tsx
src/screens/detailedPost/DetailReportSheetContent.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/UploadScreen.tsx

- BottomSheetModal의 height가 동적으로 지정되도록 하는 작업을, 실험적으로 feed와 comments의 vertical dots가 띄우는 바텀시트들에 적용해보았습니다.

[Fix][BottomSheetModal] experimentally modified BottomSheetModal to dynamically adjust its height based on its content

---

src/components/bottomsheet/SheetPostOptions.tsx
src/components/buttons/ConditionalButton.tsx
src/components/challenge/ChallengeParticipationView.tsx
src/components/comments/CommentVerticalDots.tsx
src/components/comments/SheetOthersComment.tsx
src/components/modal/TwoButtonModal.tsx
src/components/texts/StaticSizeScrollTextArea.tsx
src/screens/Feed/FeedVerticalDots.tsx
src/screens/settings/folderSettings/FolderEditScreen.tsx
src/screens/settings/folderSettings/FolderEditSection.tsx
src/screens/upload/FolderSheetContent.tsx
src/screens/upload/LinkSheetContent.tsx
src/screens/upload/UploadScreen.tsx

- upload screen 에서 바텀 시트 높이가 적절히 설정될 수 있도록 로직이 추가되었습니다.
- 여러 모달의 디자인이 틀린 부분이 보여 수정했습니다.

[Refactor][BottomSheet] upload screen 바텀시트 높이설정 & 자잘한 디자인 교정
